// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAppIOT.Models;

namespace WebAppIOT.Migrations
{
    [DbContext(typeof(IotContext))]
    [Migration("20180331132206_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppIOT.Models.System", b =>
                {
                    b.Property<int>("systemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("adressIP");

                    b.Property<double>("latitude");

                    b.Property<double>("longitude");

                    b.Property<string>("nom");

                    b.HasKey("systemID");

                    b.ToTable("system");
                });

            modelBuilder.Entity("WebAppIOT.Models.Technicien", b =>
                {
                    b.Property<int>("technicienID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cin");

                    b.Property<string>("nom");

                    b.Property<string>("prenom");

                    b.HasKey("technicienID");

                    b.ToTable("technicien");
                });

            modelBuilder.Entity("WebAppIOT.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("nom");

                    b.Property<string>("prenom");

                    b.Property<string>("pwd");

                    b.Property<int?>("systemID");

                    b.HasKey("userID");

                    b.HasIndex("systemID");

                    b.ToTable("user");
                });

            modelBuilder.Entity("WebAppIOT.Models.User", b =>
                {
                    b.HasOne("WebAppIOT.Models.System", "system")
                        .WithMany("users")
                        .HasForeignKey("systemID");
                });
#pragma warning restore 612, 618
        }
    }
}
